version: '3.9'
services:
  mongo:
    image: mongo:6
    container_name: epm_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: epm_backend
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/ebay_monitor
      - JWT_SECRET=change_me
      - ALERT_THRESHOLD_DEFAULT=5
      - ALERT_FREQUENCY_DEFAULT=immediate
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - FROM_EMAIL=${FROM_EMAIL}
    depends_on:
      - mongo
    ports:
      - "3001:3001"

  nginx:
    image: nginx:alpine
    container_name: epm_nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro

volumes:
  mongo_data:
